# Generated by Django 5.0.4 on 2024-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_activ',
            field=models.BooleanField(default=False, verbose_name='признак публикации'),
        ),
    ]
