# Generated by Django 5.0.4 on 2024-05-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_product_activ'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_edit_description', 'Can edit description'), ('can_edit_category', 'Can edit Category'), ('can_edit_product_activ', 'Can edit Product_activ')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
